MY_SCHOOL_SYSTEM/my_school/dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),

]

MY_SCHOOL_SYSTEM/my_school/my_school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schools.urls')),
    path('', include('students.urls')),
    path('', include('subjects.urls')),
    path('', include('dashboard.urls')),

]

MY_SCHOOL_SYSTEM/my_school/schools/urls.py
from django.urls import path
from . import views

app_name= 'schools'

urlpatterns = [
    path("schools/", views.school_index, name="school_index"),
    path("schools/<int:pk>/", views.school_detail, name="school_detail"),
    path("schools/add/", views.add, name="add"),

]

MY_SCHOOL_SYSTEM/my_school/students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path("students/", views.student_index, name="student_index"),
    path("students/<int:pk>/", views.student_detail, name="student_detail"),
    path("students/add/", views.add, name="add"),

]

MY_SCHOOL_SYSTEM/my_school/subjects/urls.py
from django.urls import path
from . import views

app_name = 'subjects'

urlpatterns = [
    path("subjects/", views.subjects, name="subjects"),
    path("subjects/<int:pk>/", views.subject_detail, name="subject_detail"),
    path("subjects/add/", views.add, name="add"),

]

MY_SCHOOL_SYSTEM/my_school/dashboard/models.py
from django.db import models

# Create your models here.

MY_SCHOOL_SYSTEM/my_school/schools/models.py
from django.db import models

# Create your models here.


class School(models.Model):
    name = models.CharField(max_length=100)
    code = models.TextField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=100)
    no_of_students = models.IntegerField(null=True)

    class Meta:
        db_table = 'tbl_schools'

    def __str__(self):
        return self.name

MY_SCHOOL_SYSTEM/my_school/students/models.py
from django.db import models
from schools.models import School

# Create your models here.


class Student(models.Model):
    name = models.CharField(max_length=100)
    registration_number = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    age = models.IntegerField()
    school = models.ForeignKey(School, on_delete=models.CASCADE)

    class Meta:
        db_table = 'tbl_students'

    def __str__(self):
        return self.name

MY_SCHOOL_SYSTEM/my_school/subjects/models.py
from django.db import models
from students.models import Student

# Create your models here.


class Subject(models.Model):
    name = models.CharField(max_length=100)
    score = models.IntegerField()
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    class Meta:
        db_table = 'tbl_subjects'

    # def __str__(self):
    #     return self.name
    
    def getGrade(self):
        if self.score >= 80 and self.score <= 100:
            return 'A'
        elif self.score >= 60 and self.score < 80:
            return 'B'
        elif self.score >= 40 and self.score < 60:
            return 'C'
        elif self.score >= 0 and self.score < 40:
            return 'D'
        else:
            'Unknown Grade'
    
    def __str__(self):
        return "{} - {}".format(self.name,self.getGrade())
    

MY_SCHOOL_SYSTEM/my_school/dashboard/views.py
from django.shortcuts import render
from schools.models import School

# Create your views here.


def dashboard(request):
    schools = School.objects.all()

    context = {
        'schools':schools,
    }
    return render(request, 'dashboard/dashboard.html', context)

MY_SCHOOL_SYSTEM/my_school/schools/views.py
from django.shortcuts import render,redirect
from schools.models import School
from students.models import Student

# Create your views here.


def school_index(request):
    schools = School.objects.all()
    context = {
        'schools': schools
    }
    return render(request, 'schools/schools.html', context)


def school_detail(request, pk):
    school = School.objects.get(pk=pk)
    # select * from students where school_id=x
    students = Student.objects.filter(school_id=pk)
    context = {
        "school": school,
        "students": students,
    }
    return render(request, "schools/school_detail.html", context)



def add(request):
    if request.method == "POST":
        form = request.POST
        # print(form) # for testing
        school = School()
        school.name = form['name']
        school.code = form['code']
        school.address = form['address']
        school.no_of_students = form['no_of_students']
        school.save()

        return redirect('schools:school_detail',school.pk)
    
    context = {}

    return render(request, 'schools/add.html',context)

MY_SCHOOL_SYSTEM/my_school/students/views.py
from django.shortcuts import render,redirect
from students.models import Student
from subjects.models import Subject
from schools.models import School

# Create your views here.


def student_index(request):
    students = Student.objects.all()
    context = {
        'students': students
    }
    return render(request, 'students/students.html', context)

def student_detail(request, pk):
    # select from students where student_id=x
    student = Student.objects.get(pk=pk)
    # select * from subjects where student_id = pk
    subjects = Subject.objects.filter(student_id=pk)
    

    # def getGrade(score):
    #     if score >= 80 and score <= 100:
    #         return 'A'
    #     elif score >= 60 and score < 80:
    #         return 'B'
    #     elif score >= 40 and score < 60:
    #         return 'C'
    #     elif score >= 0 and score < 40:
    #         return 'D'
    #     else:
    #         'Unknown Grade'
    
    # # grade = getGrade(score)

    context = {
        'student': student,
        'subjects':subjects,
        # 'grade':grade
    }
    return render(request, 'students/student_detail.html', context)


def add(request):
    if request.method == "POST":
        form = request.POST
        student = Student()
        student.name = form['name']
        student.registration_number = form['registration_number']
        student.address = form['address']
        student.age = form['age']
        #1
        student.school = School.objects.get(pk=form['school'])
        student.save()

        return redirect('students:student_detail',student.pk)
    
    

    schools = School.objects.all()
    context = {'schools': schools}

    return render(request, 'students/addStudent.html',context)

MY_SCHOOL_SYSTEM/my_school/subjects/views.py
from django.shortcuts import render, redirect
from subjects.models import Subject
from students.models import Student

# Create your views here.


def subjects(request):
    subjects = Subject.objects.all()
    # grade = Subject.getGrade(self=subjects)
    context = {
        'subjects': subjects,
        # 'grade':grade
    }
    return render(request, 'subjects/subjects.html', context)

def subject_detail(request, pk):
    student = Student.objects.filter(pk=pk)
    subject = Subject.objects.get(pk=pk)

    # evaluate grade
    
    context = {
        'subject':subject,
        'student':student
    }
    return render(request, 'subjects/subject_detail.html', context)

def add(request):
    if request.method == "POST":
        form = request.POST
        subject = Subject()
        subject.name = form['name']
        subject.score = form['score']
        subject.student = Student.objects.get(pk=form['student'])
        subject.save()

        return redirect('subjects:subject_detail',subject.pk)
    
    students = Student.objects.all()
    context = {
        'students':students,
        'subjects':subjects
    }

    return render(request, 'subjects/addSubject.html',context)

MY_SCHOOL_SYSTEM/my_school/schools/templates/schools/add.html
{% extends 'base.html' %}
{% block content %}
       <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Add A School</h1>
          </div>

        <form action="{% url 'schools:add' %}" method="post" name="fromSchool">
            {% csrf_token %}
            <label for="name">Name: </label>
            <input type="text" id="name" name="name" > 
            <br>
            <br>
            <label for="name">Code: </label>
            <input type="text" id="code" name="code"> 
            <br>
            <br>
            <label for="name">Address: </label>
            <input type="text" id="address" name="address"> 
            <br>
            <br>
            <label for="name">No Of Students: </label>
            <input type="number" id="name" name="no_of_students"> 
            <br>
            <br>
            <input type="submit" value="Save">
        </form>

        </main>
      </div>
    </div>

    
{% endblock %}

MY_SCHOOL_SYSTEM/my_school/schools/templates/schools/school_detail.html
{% extends 'base.html' %}

{% block content %}

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">School Details</h1>
          </div>

            <p> Name:  {{ school.name }} </p>
            <p> Code:  {{ school.code }} </p>
            <p> Address: {{ school.address }} </p>
            <p> No of Students: {{ school.no_of_students }} </p>
            <hr>

          <h1 class="h2">Students at {{ school.name }}</h1>
          <div class="table-responsive">
           <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Reg No</th>
              <th>Address</th>
              <th>Age</th>

            </tr>
          </thead>
          <tbody>
           <tr>
          {% for student in students %}
          <td> <a href="{% url 'students:student_detail' student.id %}">{{ student.id }} </a> </td>
          <td> {{ student.name }} </td>
          <td> {{ student.registration_number }} </td>
          <td> {{ student.address }} </td>
          <td> {{ student.age }} </td>
        </tr>
        {% endfor %} 
		  </tbody>
        </table>
          </div>
        </main>
      </div>
    </div>
    
{% endblock  %}

MY_SCHOOL_SYSTEM/my_school/schools/templates/schools/schools.html
{% extends 'base.html' %}

{% block content %}

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">List of Schools</h1>
            <a href="{% url 'schools:add' %}">Add A School</a>
          </div>

          <div class="table-responsive">
           <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Address</th>
            </tr>
          </thead>
          <tbody>
            <tr>
            {% for school in schools %}
              <td> <a href="{% url 'schools:school_detail' school.id %}">{{ school.id }}</a></td>
              <td> {{ school.name }} </td>
              <td> {{ school.address }} </td>
            </tr>
            {% endfor %}
		  </tbody>
        </table>
          </div>
        </main>
      </div>
    </div>
    
{% endblock  %}

MY_SCHOOL_SYSTEM/my_school/students/templates/students/addStudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add a Student</title>
</head>
<body>
    <h2>Add a Student</h2>
        <form action="{% url 'students:add' %}" method="post" name="fromStudent">
            {% csrf_token %}
            <label for="name">Name: </label>
            <input type="text" id="name" name="name" > 
            <br>
            <br>
            <label for="name">Reg No: </label>
            <input type="text" id="code" name="registration_number"> 
            <br>
            <br>
            <label for="name">Address: </label>
            <input type="text" id="address" name="address"> 
            <br>
            <br>
            <label for="name">Age: </label>
            <input type="number" id="name" name="age"> 
            <br>
            <br>
            <label for="name">School: </label>

            <select name="school" id="">
            <option value="">Select a school</option>
            {% for school in schools %}
                <option value="{{ school.id }}">{{ school.name }}</option>

            {% endfor %}
            
            </select>
            

            <input type="submit" value="Save">
        </form>
</body>
</html>

MY_SCHOOL_SYSTEM/my_school/students/templates/students/student_detail.html
{% extends 'base.html' %}
{% block content %}

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Student Details</h1>
          </div>
          <p>Name: {{ student.name }}</p>
          <p>Reg No: {{ student.registration_number }}</p> 
          <p>Address: {{ student.address }}</p> 
          <p>Age: {{ student.age }}</p> 
          <p>School: {{ student.school }}</p>
          <hr>

            <h1 class="h2">Report Form </h1>
          <div class="table-responsive">
           <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>Subject</th>
              <th>Score</th>
              <th>Grade</th>
            </tr>
          </thead>
          <tbody>
             {% for subject in subjects  %}
              <tr>
                <td> {{ subject.name }} </a> </td>
                <td> {{ subject.score }} </td>      
            {% endfor %}
            </tr>
		  </tbody>
        </table>
        <br>
        <p>Total Score:   {{ grade }}</p>
        <p>Mean Grade: </p>
          </div>
        </main>
      </div>
    </div>
    
{% endblock  %}

MY_SCHOOL_SYSTEM/my_school/students/templates/students/students.html
{% extends 'base.html' %}

{% block content %}
  
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">List of Students</h1>
          </div>
          <div class="table-responsive">
           <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Reg No</th>
              <th>Address</th>
              <th>Age</th>
              <th>School</th>
            </tr>
          </thead>
          <tbody>
          <tr>
              {% for  student in students %}
              <td><a href="{% url 'students:student_detail' student.id %}">{{ student.id }}</a></td>
              <td> {{ student.name }} </td>
              <td> {{ student.registration_number }} </td>
              <td> {{ student.address }} </td>
              <td> {{ student.age }} </td>
              <td> {{ student.school }} </td>
          </tr>
        {% endfor %}
		  </tbody>
        </table>
          </div>
        </main>
      </div>
    </div>
    
{% endblock  %}
 

MY_SCHOOL_SYSTEM/my_school/subjects/templates/subjects/addSubject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add a Student</title>
</head>
<body>
    <h2>Add a Subject</h2>
        <form action="{% url 'subjects:add' %}" method="post" name="fromStudent">
            {% csrf_token %}
            <label for="name">Name: </label>
            <input type="text" id="name" name="name" > 
            <br>
            <br>
            <label for="name">Score </label>
            <input type="number" id="score" name="score"> 
            <br>
            <br>
            <label for="name">Select student: </label>

            
            <select name="student" id="">
            <option value="">Select a student</option>
            {% for student in students %}
                <option value="{{ student.id }}">{{ student.name }}</option>
            {% endfor %}

            <br>
            <br>
            <input type="submit" value="Save">
        </form>
</body>
</html>

MY_SCHOOL_SYSTEM/my_school/subjects/templates/subjects/subject_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Subject Details</title>
</head>
<body>
   <a href="{% url 'subjects:add' %}">Back to Add Subject</a>

  <h2>Details of Subject You've Just Added</h2>
  
    <p>Name: {{ subject.name }}</p>
    <p>Score: {{ subject.score }}</p> 
    <p>Student Name: {{ subject.student }}</p> 
    
 
  <hr>
  
  



</body>
</html>

MY_SCHOOL_SYSTEM/my_school/subjects/templates/subjects/subjects.html
{% extends 'base.html' %}

{% block content %}
       <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">List of Subjects</h1>
          </div>
          <div class="table-responsive">
           <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>Name</th>
              <th>Score</th>
              <th>Student</th>
            </tr>
          </thead>
          <tbody>
             {% for  subject in subjects %}
              <td> {{ subject.name }}</td>
              <td> {{ subject.score }} </td>
              <td> {{ subject.student }} </td>
            </tr>
             {% endfor %}
		  </tbody>
        </table>
          </div>
        </main>
      </div>
    </div>
    
{% endblock  %}
 

MY_SCHOOL_SYSTEM/my_school/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>School System</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
</head>
<body>
     
    <!-- Nav-->
     <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'schools:school_index' %}">My School System</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="#">Sign out</a>
        </li>
      </ul>
    </nav>

    <!-- Menu -->
    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="#">
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'schools:school_index' %}">
                  <span data-feather="file"></span>
                      Schools
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'students:student_index' %}">
                  <span data-feather="shopping-cart"></span>
                      Students
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'subjects:subjects' %}">
                  <span data-feather="users"></span>
                      Subjects
                </a>
              </li>

            </ul>

         
          </div>
        </nav>

    {% block content %}

    {% endblock %}
</body>
</html>
    

MY_SCHOOL_SYSTEM/my_school/templates/dashboard/dashboard.html
{% extends 'base.html' %}

{% block content %}
  <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">My School System</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="#">Sign out</a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="#">
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'schools:school_index' %}">
                  <span data-feather="file"></span>
                      Schools
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'students:student_index' %}">
                  <span data-feather="shopping-cart"></span>
                      Students
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'subjects:subjects' %}">
                  <span data-feather="users"></span>
                      Subjects
                </a>
              </li>

            </ul>

         
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">List of Schools</h1>
          </div>

          <div class="table-responsive">
           <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Address</th>
            </tr>
          </thead>
          <tbody>
            <tr>
            {% for school in schools %}
              <td> <a href="{% url 'schools:school_detail' school.id %}">{{ school.id }}</a></td>
              <td> {{ school.name }} </td>
              <td> {{ school.address }} </td>
            </tr>
            {% endfor %}
		  </tbody>
        </table>
          </div>
        </main>
      </div>
    </div>
    
{% endblock  %}